force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/jobSearchController.cls
public with sharing class jobSearchController {
    @AuraEnabled(cacheable=true)
    // The method now accepts a 'searchKey' string from the LWC
    public static List<Job__c> findOpenJobs(String searchKey) {
        // If the search key is not blank, add wildcards (%) for a partial match search.
        // Otherwise, make the key a wildcard to find all jobs.
        String searchKeyWithWildcards = '%' + searchKey + '%';

        return [
            SELECT Id, Name, Hiring_Manager__r.Name
            FROM Job__c
            WHERE Status__c = 'Open'
            AND Name LIKE :searchKeyWithWildcards
            ORDER BY CreatedDate DESC
        ];
    }
}